### ISSUE TITLE
Php Error if only one match case. 

### ISSUE THREAD

**Issue by BrookeDot** [chadsmith/OpenVBX-Plugin-Match#1]
I seem to get the following error if I only use one match case and hit save. 

```
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: match/ui.php

Line Number: 36
```

 If I have two cases that do the same action I don't have this problem.

**Comment by chadsmith** [comment]
Sorry, I forgot to push the update. It should work now.

**Comment by BrookeDot** [comment]
Thanks for the quick response. I'm now having an issue where if I only use one match case and hit safe it removes all input options from the match plugin. This is the same issue I had when I fixed the array issue by checking if the foreach() was empy. I thought I did something wrong so I posted here. 

I also added a screenshot of this issue: ![Match Screenshot](http://i784.photobucket.com/albums/yy129/BandonRandon_dev/sms-match-error.png)
