### ISSUE TITLE
Matches dropping from flow

### ISSUE THREAD

**Issue by BryanGriffith** [chadsmith/OpenVBX-Plugin-Match#2]
After I create a flow and add matches the flow is becoming corrupted and I will be left with only 1 match. What am I doing wrong?

**Comment by BryanGriffith** [comment]
That error is occurring on an install of OpenVBX 1.03, but is not occurring on an install of OpenVBX 0.9 r47. I am going to try a complete reinstall of 1.0 and see what happens.

**Comment by chadsmith** [comment]
I wasn't able to reproduce the issue in v1.0.3 r52. Is it doing it on the new install?

**Comment by BryanGriffith** [comment]
No, it was not. I switched to using FireFox from Chrome and a number of my
problems went away.

Bryan M. Griffith, J.D.

Bryan@BryanGriffith.com
http://bryangriffith.com/
BryanGriffith.com http://bryangriffith.com/
http://www.linkedin.com/in/bryangriffith
http://www.twitter.com/BryanGriffith

**Comment by chadsmith** [comment]
Turns out it was an issue with jQuery 1.6. Try the latest version.

**Comment by BryanGriffith** [comment]
Thanks Chad!

Bryan M. Griffith, J.D.

Bryan@BryanGriffith.com
http://bryangriffith.com/
BryanGriffith.com http://bryangriffith.com/
http://www.linkedin.com/in/bryangriffith
http://www.twitter.com/BryanGriffith
