### ISSUE TITLE
Flow issue

### ISSUE THREAD

**Issue by curtiswaters** [chadsmith/OpenVBX-Plugin-Match#3]
Using chadsmith-OpenVBX-0.91-0-g537ce22
chadsmith-OpenVBX-Plugin-Match-bd2cbe1
chadsmith-OpenVBX-Plugin-Subscriptions-7457e14

I have a flow setup as follows:

Match -->  stop -->send a reply
           -->  keyword --> if member --> Member --> send reply
                                                            --> Non Members --> subscription

If I click Add & Remove + next to any any Match applet (stop or keyword) to add another match applet, I am taken on Chrome & Safari back to the Match screen - IE9 produces PHP errors

Any ideas on how to resolve?

**Comment by chadsmith** [comment]
Is IE9 giving a PHP error or JavaScript error? My guess is it's JavaScript and is caused from the plugin using a newer version of jQuery than that version of OpenVBX. Update to [1.0.3](https://github.com/twilio/OpenVBX) and it should go away.

**Comment by curtiswaters** [comment]
Thanks - that fixed it!

On Mon, Aug 29, 2011 at 11:33 AM, chadsmith <
reply@reply.github.com>wrote:

> Is IE9 giving a PHP error or JavaScript error? My guess is it's JavaScript
> and is caused from the plugin using a newer version of jQuery than that
> version of OpenVBX. Update to [1.0.3](https://github.com/twilio/OpenVBX)
> and it should go away.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/chadsmith/OpenVBX-Plugin-Match/issues/3#issuecomment-1932241

## 

Curtis Waters
