### ISSUE TITLE
Matches dropping from flow

### ISSUE THREAD

**Issue by jumpfire** [chadsmith/OpenVBX-Plugin-Match#4]
Previous "Matches dropping from flow" issue is still there?

Downloaded latest versions still unable to add more than one keyword?

Anyone else experiencing this?

Thanks for any advice...

PS i somehow added a fork - was accident don't know how to delete it???

**Comment by chadsmith** [comment]
What browser and version of OpenVBX are you using? Do any JavaScript errors show up, or does it do anything when you click to add another keyword?

**Comment by jrgkgb** [comment]
I'm having the same issue - I can save up to two keywords but that's it, it "forgets" anything additional I use.  I'm on Win7 using Google Chrome.  Latest version of OpenVBX, just downloaded and installed today.

**Comment by jrgkgb** [comment]
Same behavior in Firefox.

**Comment by jrgkgb** [comment]
Getting errors in IE also:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.2; AskTbTRL2/5.7.0.231)
Timestamp: Wed, 7 Sep 2011 07:24:02 UTC

Message: Object expected
Line: 2177
Char: 3
Code: 0
URI: http://voice.pressplatform.com/flows/sms/2

Message: Can't execute code from a freed script
Line: 21
Char: 31
Code: 0
URI: http://voice.pressplatform.com/assets/j/plugins/jquery.address-1.0.min.js

Message: Can't execute code from a freed script
Line: 21
Char: 31
Code: 0
URI: http://voice.pressplatform.com/assets/j/plugins/jquery.address-1.0.min.js

Message: 'console' is undefined
Line: 24
Char: 3
Code: 0
URI: http://voice.pressplatform.com/

**Comment by jumpfire** [comment]
thanks for the quick response everyone! i have this plugin working on chadsfork a few months ago - but wasnt able to get it working on the new version of openvbx

as of this morning am using firefox/win7pro

i can add 2 keywords - when i add a 3rd or more and then save and close when i re-open it only displays the last entry that was added

am gettting a lot of repeat errors related to this
http://domain.com/assets/j/compiled/1011/site.js
line 145

when i say a lot i mean like 50+ lol

clean install:

twilio-OpenVBX-1.0.4-0-g3b9f6e7.zip
chadsmith-OpenVBX-Plugin-Match-bd2cbe1.zip

**Comment by jumpfire** [comment]
oops didnt mean to close then - not had morning coffee yet!

**Comment by chadsmith** [comment]
I haven't been able to reproduce the issue in 1.0.4. Do you have any other plugins installed?

**Comment by jumpfire** [comment]
yeah a bunch of your other plugins :)

I will do a new install right now with just the match plugin and see if that makes a difference...

**Comment by jumpfire** [comment]
sorry keep hitting the close issue instead of comment button!

**Comment by jumpfire** [comment]
hi chad - just did a brand new install - just the match plugin and still same issue

works fine with first 2 match keywords

add the third and save then go back in to it the previous two keywords will disappear and only the third keyword will be visible

i can give you login credentials if you like?

**Comment by jrgkgb** [comment]
I just had the same experience, happy to provide login creds as well.

**Comment by jumpfire** [comment]
i just did this quick video showing the problem - this is on a brand new install just 20 mins ago and only the match plugin enabled... also freshly downloaded and installed....

http://www.screenr.com/k5Cs

hope that helps... am using win7pro/firefox 6.0.2

**Comment by jrgkgb** [comment]
Yup - that's what happened to me.  May be worth mentioning, if you do 4 keywords, it will keep 2.

**Comment by jumpfire** [comment]
Chad what configuration do you have set up so that its working? ie what browser/host are you using

Personally without this plugin working there's no point in me installing the latest version of Openvbx

Thanks in advance

**Comment by dcc1784** [comment]
Hi Chad, same issue here with v 1.0.4 all browsers, also seems to do something similar with your split test plugin. You can add two applets with no problem, but add 3 and they all dissapear after save.

**Comment by buzz2** [comment]
This is the same thing on my end. Fresh install, can only add 2 events.

**Comment by jumpfire** [comment]
Chad can you show us a working version please so as i can replicate it? I will pay if need be to get this working! Without it like i said before the current version of OpenVBX for me is useless....

**Comment by jumpfire** [comment]
i hate the position of the close issue button!!!!!

**Comment by chadsmith** [comment]
Found the issue. I just pushed out a fix.
